### ISSUE TITLE
Unexpected deadlock with AsyncStream

### ISSUE THREAD

**Issue by zshannon** [groue/Semaphore#14]
Hey there, thanks for sharing this excellent library! I'm sorry to say I'm running into an unexpected deadlock where my AsyncStream's onTermination handler doesn't execute while I'm waiting for the semaphore. Here's a brief demo of the problem as a playground:

<img width="1052" alt="Screenshot 2024-08-12 at 4 54 46 PM" src="https://github.com/user-attachments/assets/cd537edc-2322-42ea-9007-78e6f5daa8b3">

[Above code as gist](https://gist.github.com/zshannon/dc6addcba474d92c46edd4748c40eb6c)

Please let me know if there's anything I can clarify to help debug

**Comment by mman** [comment]
@zshannon I think you never call `finish` on a stream and therefore its onTermination is not called and therefore semaphore is never signaled…

**Comment by zshannon** [comment]
On line 13 I yield 0 which leads to breaking on line 37. Same code works with changing to Task.sleep (see lines 40-43).

**Comment by mattmassicotte** [comment]
Ok, so here's what's going. At the end of the `unreferenced` function, the `stream` will be deallocated. This is the only code path that currently can invoke the `onTermination` handler. This will happen with or without a sleep.

But, when that semaphore is waited, the deallocation never happens, stream never terminates, and so the semaphore never gets signalled. I think this is working correctly. Just tricky!

**Comment by groue** [comment]
I would suggest running the sample code in a regular package or Xcode project, in order to use breakpoints and other debugging techniques, and check assumptions. Playgrounds aren't the best debugging tool.

As mentioned above, the termination handler is probably not called, and the sample code does not reveal any issue with the Semaphore library.

**Comment by zshannon** [comment]
Aha I see now, I expected the compiler to understand at the point I suspend for the semaphore that the context can be cleaned up and that's not the case so the termination handler isn't being invoked by dealloc. Thanks for thinking about it, appreciate the attention.
